service: aws-node-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "dev"}
  environment:
     ${file(./config/${opt:stage, 'dev'}.yaml)}

functions:
   websocketConnect: ${file('./deploy/functions/WebSocketConnect.yaml')}
   websocketDisconnect: ${file('./deploy/functions/WebSocketDisconnect.yaml')}
   websocketOnMessage: ${file('./deploy/functions/WebSocketOnMessage.yaml')}

package:
   individually: true
   patterns:
       - '!deploy/**'
       - '!config/**'
       - '!src/**'
   exclude:
       - layer/**
layers:
   AWSSDKDependenciesNodeModule:
       path: layer
       description: "aws sdk dependencies"

plugins:
   - serverless-iam-roles-per-function
   - serverless-pseudo-parameters
resources:
   Resources:
       ConnectionsWebsocketTable: ${file(./deploy/resources/ConnectionsWsDynamoDb.yaml)} 
    
